# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: 시리의 다시 보는 개발페이지

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: SeonYoung Lee - siri

description: Stylish Jekyll Theme
author:
  name: SeonYoung Lee - siri
  email: sylee010101@gmail.com
  github: siri-syl
  twitter: 
  pinterest: 
  linkedin: 
  bio: 노션 쓰다가 안되겠다 싶어서 다시 만든 깃허브 블로그! \n 정신 차려 네가 적은 거 잊지 마!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
