# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: SY.Lee - siri

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 시리의 다시 보는 개발페이지

description: Stylish Jekyll Theme
author:
  name: SY.Lee - siri
  email: sylee010101@gmail.com
  github: siri-syl
  twitter: 
  pinterest: 
  linkedin: 
  bio: 개발하다 다시 보기 위한 깃허브 블로그!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
